---
AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Role for Github OIDC provider

Resources:
  GithubOIDCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GithubOIDCRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: repo:moritzkoerber/data-engineering:*
      Path: /
      Policies:
        - PolicyName: Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:*
                Resource:
                  - !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/api_lambda'
                  - !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/ge_lambda'
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource:
                  - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*'
              - Effect: Allow
                Action:
                  - s3:*
                  - iam:*
                  - glue:*
                  - lambda:*
                  - events:*
                  - cloudwatch:*
                  - logs:*
                Resource: '*'
                Condition:
                  StringEquals:
                    aws:CalledViaFirst: cloudformation.amazonaws.com
