---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.285"
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.79.7
    hooks:
      - id: cfn-python-lint
        files: ops/stack/.*.yaml$

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.24.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
        types_or: [javascript]
