---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.6"
    hooks:
      - id: ruff
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.83.3
    hooks:
      - id: cfn-python-lint
        files: ops/stack/.*.yaml$
        args: [--ignore-checks, W3045]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.27.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript]
