repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-toml
    - id: check-yaml
      args:
        - '--unsafe'

- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort

- repo: https://github.com/humitos/mirrors-autoflake
  rev: v1.3
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8

- repo: https://github.com/aws-cloudformation/cfn-lint
  rev: v0.58.0
  hooks:
    - id: cfn-python-lint
      files: ops/stack/.*.yaml$

- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.10.2
  hooks:
    - id: check-github-workflows
    - id: check-github-actions
