repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
    - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.9.2
  hooks:
    - id: isort

- repo: https://github.com/humitos/mirrors-autoflake
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8

- repo: https://github.com/aws-cloudformation/cfn-python-lint
  rev: v0.52.0
  hooks:
    - id: cfn-python-lint
      files: ops/stack/.*.yaml$
