AWSTemplateFormatVersion: '2010-09-09'
Description: Data Engineering Project Stack

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: data-engineering-project-s3-bucket
